"""
Football Player Scouting & Recruitment Intelligence Platform - home page.

Run with:  streamlit run app.py
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from src.config import POSITION_GROUP_NAMES
from src.ui import badges, eyebrow, note, page_setup, sidebar_filters, tiles

page_setup("Home", "🏠")
platform = sidebar_filters()

pool = platform.pool

st.markdown(
    """
<div class="sx-hero">
  <div class="sx-eyebrow">Recruitment analytics</div>
  <h1 style="margin:0.1rem 0 0.5rem 0;">Scouting Intelligence</h1>
  <div style="font-size:1.02rem; color:#c3c2b7; max-width:74ch;">
    Find statistically similar players, define a recruitment profile and get a ranked
    shortlist, and read a player's strengths and weaknesses against his positional peers -
    with the arithmetic behind every number on show.
  </div>
</div>
""",
    unsafe_allow_html=True,
)

st.write("")
tiles(
    [
        ("Player-seasons", f"{len(pool):,}", f"min {platform.min_minutes:,} minutes"),
        ("Players", f"{pool['player_id'].nunique():,}", "unique identities"),
        ("Leagues", f"{pool['league'].nunique()}", f"{pool['team'].nunique()} clubs"),
        ("Seasons", f"{pool['season'].nunique()}", ", ".join(platform.seasons)),
        ("Position models", f"{len(platform.models)}", "fitted independently"),
        (
            "Archetypes",
            f"{sum(m.clusters.k for m in platform.models.values())}",
            "generated from cluster centroids",
        ),
    ]
)

st.warning(
    "**This app runs on a simulated dataset.** Real season data (FBref, Opta, StatsBomb) cannot "
    "be redistributed here, so the reference dataset is generated by a latent-trait simulation: "
    "players are drawn from role profiles, and their season totals are *sampled* over their actual "
    "minutes, so small samples are genuinely noisy. The names are invented and nothing in this app "
    "describes a real footballer. Every model, score and chart is built to run unchanged on a real "
    "player-season export - see **Methodology** for the ingestion path.",
    icon="⚠️",
)

left, right = st.columns([1.05, 1])

with left:
    st.markdown("## What it answers")
    st.markdown(
        """
- **Who resembles this player?** Nearest neighbours in a standardised, position-specific
  feature space - with a feature-by-feature account of *why*.
- **Which young player resembles an established one?** The same search, filtered by age and
  league level.
- **Who fits our brief?** Hard filters plus a weighted fit score across attribute categories.
- **What is this player good and bad at?** Percentiles against positional peers, never
  against the whole dataset.
- **What kind of player is he?** A K-Means archetype whose label is written from the cluster's
  own centroid.
- **Who is being overlooked?** A transparent composite of output, age, minutes, league exposure
  and statistical rarity.
"""
    )

with right:
    st.markdown("## How to use it")
    st.markdown(
        """
1. Set the **minimum minutes** in the sidebar - it defines the pool every number is measured
   against, and the models refit when you change it.
2. **Player Search** to find someone, then **Player Profile** for the full read-out and a
   downloadable scouting report.
3. **Similar Players** for the nearest-neighbour engine and its explanations.
4. **Recruitment Finder** to turn a brief into a shortlist.
5. **Compare Players**, **Player Archetypes**, **Hidden Gems** and **League Explorer** for the
   wider population.
6. **Model Validation** for the sensitivity tests, and **Methodology** for every formula.
"""
    )

st.markdown("## Pool composition")
composition = (
    pool.groupby("position_group")
    .agg(
        players=("player_id", "nunique"),
        seasons=("player_id", "size"),
        median_minutes=("minutes", "median"),
        median_age=("age", "median"),
    )
    .reindex([g for g in POSITION_GROUP_NAMES if g in pool["position_group"].unique()])
    .reset_index()
)
composition["position_group"] = composition["position_group"].map(
    lambda g: f"{g} - {POSITION_GROUP_NAMES[g]}"
)
composition["archetypes"] = [
    platform.models[g].clusters.k if g in platform.models else 0
    for g in pool.groupby("position_group").size().reindex(
        [c.split(" - ")[0] for c in composition["position_group"]]
    ).index
]

st.dataframe(
    composition.rename(
        columns={
            "position_group": "Position group",
            "players": "Players",
            "seasons": "Player-seasons",
            "median_minutes": "Median minutes",
            "median_age": "Median age",
            "archetypes": "Archetypes (k)",
        }
    ),
    hide_index=True,
)

st.markdown("## Data quality report")
note(
    "Produced by <code>src/data_processing.clean_players</code> on every load. Rows are dropped "
    "only when a value makes the per-90 arithmetic impossible; everything else is repaired or "
    "imputed and counted here."
)
report = pd.DataFrame(platform.cleaning.as_rows(), columns=["Check", "Rows"])
st.dataframe(report, hide_index=True, height=380)
for line in platform.cleaning.notes:
    st.caption(line)

st.markdown("## Where the models draw the line")
columns = st.columns(3)
with columns[0]:
    eyebrow("Descriptive")
    st.markdown(
        "Per-90 rates, success percentages, percentiles. These are **measurements** of what "
        "happened, subject only to sample size."
    )
with columns[1]:
    eyebrow("Model output")
    st.markdown(
        "Similarity scores, archetypes, fit scores, hidden-gem scores. These are **constructed** "
        "from the measurements and inherit the assumptions listed in Methodology."
    )
with columns[2]:
    eyebrow("Not available")
    st.markdown(
        "Transfer fees, wages, contract length, injury history. Nothing here is a valuation, "
        "and no score should be read as one."
    )

st.write("")
badges(
    [
        ("Python", ""), ("pandas", ""), ("NumPy", ""), ("scikit-learn", ""),
        ("Plotly", ""), ("Streamlit", ""),
    ]
)
